apiVersion: cassandra.k8ssandra.io/v1alpha1
kind: CassandraRestore
metadata:
  name: test-1
spec:
  backup: test-1
  inPlace: true
  shutdown: true
  cassandraDatacenter:
    name: dc1
    # The CRD currently requires clusterName but the operator uses reuses the cluster name
    # from the backup CassandraDatacenter
    clusterName: medusa-test

